### PR TITLE
Fix jobmanager port assignment in HA mode, bump flink 1.1.3

### PR DESCRIPTION
**Pull request by blendmaster**
Was getting randomized since the default value is 0.
This extra-special "recovery.joibmanager.port" config
isn't even documented, but I found it poking through the source.

Flink 1.2 is supposed to have proper mesos support, probably
obviating this repo completely, but until then, this helps.

### CODE REVIEW

**Comment by tobilg** [comment]
Thanks for the PR! I'd like to understand why this is necessary, because we're running the existing version without problems.

Furthermore it's not possible to assign the same port twice, it won't work.

**Comment by tobilg** [comment]
I don't find any info on this property, and as I said, it works without. Currently, I see no use in merging this tbh.

**Comment by blendmaster** [comment]
I finally found docs for it:

https://ci.apache.org/projects/flink/flink-docs-release-1.1/setup/jobmanager_high_availability.html#masters-file-masters

>By default, the job manager will pick a random port for inter process communication. You can change this via the recovery.jobmanager.port key. This key accepts single ports (e.g. 50010), ranges (50000-50025), or a combination of both (50010,50011,50020-50025,50050-50075).

Oddly, it's from a year-old PR https://github.com/apache/flink/pull/1458 , so I'm not sure why only I seemed to run into the issue.

Do the logs for your flink jobmanagers mention what akka port they're using? Without this change, my jobmanagers would register something like `akka.tcp://x.x.x.x:45678` into zookeeper, and the taskmanagers would subsequently fail to connect. Perhaps there's also something more restrictive about my docker or mesos configuration? FWIW, I'm on `mesos-1.0.1-2.0.93.ubuntu1404` and 

```
$ sudo docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
```

**Comment by tobilg** [comment]
There's no mention of it in the configuration docs at https://ci.apache.org/projects/flink/flink-docs-release-1.1/setup/config.html#high-availability-mode

So one of the docs pages must be false. Like I said, we're running Flink clusters with this image without a problem.

Also, assigning the `PORT0` twice won't work anyway.

**Comment by blendmaster** [comment]
>There's no mention of it in the configuration docs at https://ci.apache.org/projects/flink/flink-docs-release-1.1/setup/config.html#high-availability-mode

I noticed that too, but it definitely has an effect in flink 1.1.3 https://github.com/apache/flink/blob/release-1.1.3/flink-runtime/src/main/scala/org/apache/flink/runtime/jobmanager/JobManager.scala#L2389

Once https://github.com/mesoshq/flink-framework/issues/2 is merged I'll try again with the official image.

**Pull request closed without merging**
